aligent/serverless-aws-nodejs-service-template

package.json

These packages should never be required at run time. Webpack is probably excluding them anyway but best to be safe.

moving local s3, dynamodb, serverless offline to devdependencies

---

webpack.config.js

Webpack 5 is more strict about the order of options in the devtools string.
See: https://webpack.js.org/configuration/devtool/

reworking devtool configuration to match webpack 5 requirements

---

README.md
serverless.yml

Running docker-compose up with the dynamodb-local plugin gives a cryptic error if the dynamodb libraries haven't been installed yet.
Either the readme should include this as a required step or that plugin should not be active by default. I've chosen the latter as not all services will need dynamodb.

Commented out local dynamodb plugin in serverless.yml

---

.vscode/serverless.code-snippets

Not 100% necessary but a standard snippets file could help onboard people and speed up development a bit.

Adding a local snippets file for to put common boilerplate handler code

---

package.json

Adds the NPM `--coverage` flag to NPM test step.
This will output a pretty coverage report.

Add code coverage flag to test step

---

serverless.yml

Adds [CloudFormation service role](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-servicerole.html) parameter to template.
To encourage security best practices I believe the default should be to deploy using a CloudFormation service role as opposed to deploying using the IAM privileges of the deploy context.

Adds CloudFormation service role parameter to template

---

.gitignore
jest.config.js

Add [Jest coverage thresholds](https://jestjs.io/docs/configuration) of 80% to branches, functions, lines and statements.
I think 80% is a good default. If projects chose to remove / lower this at least it is intentional.

Add test coverage thresholds

---

serverless.yml
tsconfig.json

AWS supports node 14 (https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/) so update the template to reflect that.
Also tweaked the tsconfig to match recommended settings (https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping)

Upgrade to use AWS node 14 runtime

---

serverless.yml

Because I only added it to the package.json and didn't actually add it to the serverless.yml file for some reason. (PR #285 )

Added the conventions plugin to serverless.yml

---

package-lock.json
serverless.yml

This PR removes the CFN deployment role from the template.
This is no longer necessary as our pipelines can inject this at deploy time.
[Related PR](https://github.com/aligent/serverless-deploy-pipe/pull/2).

Remove CloudFormation service role

---

package-lock.json
package.json

This is an obsolete dependency, which among other things brings webpack in to our node_modules unnecessarily

Uninstall ts-loader

---

.eslintignore
jest.config.js

ts-jest started giving warnings about deprecated syntax in jest configuration. This PR implements the suggested new syntax.
Also ignoring jest config in eslint as it otherwise gives a warning about not being included in tsconfig spec

Replace Globals/preset spec with transform syntax

---

package.json

An entry point doesn't really make sense here, and handler.js doesn't exist.

#596 remove `main` entry from package.json

---

package-lock.json
package.json

Serverless is already installed as a peer dependency of several plugins.
Unfortunately this does not cause dependabot to keep the package version up to date, leading to unexpected behaviour when deploying with serverless.
Including the framework as a dev dependency should ensure we always have an up to date version installed for plugins to use.

Include serverless in dev dependencies

---

.eslintrc.json

Added the array-callback-return eslint rule to the base eslintrc json file. 
Only set the level as error and did not set any options as the defaults make sense

Added the array-callback-return eslint rule to the base eslintrc json file

---

tools/serverless-plugin/tsconfig.json
tsconfig.base.json

The tsconfig being extended in tsconfig.base.json already specifies "moduleResolution": "node16"
"moduleResolution": "node" is for earlier versions of NodeJS
This is being picked up as an error in service tsconfigs that extend tsconfig.base.json: `Option 'moduleResolution' must be set to 'Node16' (or left unspecified) when option 'module' is set to 'Node16'.`

chore: Remove override of module resolution

---

vite.config.base.ts

Since we switched to v8 coverage, vitest complains about our types files:
This PR exclude all the `types` folder in vitest coverage report to prevent this issue.

MICRO-349: Exclude types folder from test coverage

---

bitbucket-pipelines.yml

Adds a manual approval button step before a production deploy.
Removes the test deployment as it was causing more problems than it was solving :(
CloudFormation would rarely clean up after itself on a stack destroy so we were left with dangling resources.

Wait for production deploy in bitbucket pipeline

---

.eslintrc.json

It's often useful to be able to discard properties from an object using `{ prop, ...rest } = obj` syntax, or mark unused function arguments with `_` prefix. This change modifies the `no-unused-vars` linting rule to allow both.

Chore: Allow unused vars in rest object spreading or prefixed with uderscore

---

bitbucket-pipelines.yml
package-lock.json
package.json

This PR update:
- the pipeline version to the latest one
- increase node version to 20.18 to match with pipeline version
- I also run `npm audit fix` to fix some vulnerabilities

Update pipeline & npm audit fix

---

tools/serverless-plugin/src/generators/service/notification-files/src/lambda/notify-error.ts.template
tools/serverless-plugin/src/generators/service/notification-files/src/utils/aws-formatting.ts.template
tools/serverless-plugin/src/generators/service/notification-files/tests/aws-formatting.test.ts.template

Fail steps don't produce a JSON string, rather they just provide the error detail as-is (typically just a message). So we catch that failure and check whether the source is `aws.states` which then prompts us to return the error as-is.

Feature: Support AWS StepFunctions Fail steps

---

README.md

Passing `scope` means the service stacks don't inherit things like the stage tag.

MI-262: (fix) ensure example service instantiation works

---

README.md

Straightforward documentation change to avoid an error caused by running all three commands in one.

MI-259: Fix step 2 of setup documentation
